name: deploy

on: 
  push:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    # js 파일 실행
    - name: Build source file
      run: npm run start
      env: 
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        PORT: ${{ secrets.PORT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    # Docker hub 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PW }}
    # 도커이미지 빌드, 푸시
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: |
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          PORT=${{ secrets.PORT }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
        push: true
        file: ./Dockerfile
        tags: shkilo/halgoraedo
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_email: "ironjustlikethat@gmail.com"
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "kakao-sw02-backend"
      env:
        MONGODB_URI: ${{secrets.MONGODB_URI}}
        PORT: ${{secrets.PORT}}
        SECRET_KEY: ${{secrets.SECRET_KEY}}